FROM python:3.10-slim

ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_NAME=nuScene

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install python-dotenv

CMD ["python", "dbconnect.py"]
